// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: resume.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//-----------------------记录请求 start------------------
type ResumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerName string `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Ip         string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	IpAddr     string `protobuf:"bytes,3,opt,name=ip_addr,json=ipAddr,proto3" json:"ip_addr,omitempty"`
	Result     string `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resume_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_resume_proto_rawDescGZIP(), []int{0}
}

func (x *ResumeRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ResumeRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ResumeRequest) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

func (x *ResumeRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ResumeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResumeReply) Reset() {
	*x = ResumeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resume_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeReply) ProtoMessage() {}

func (x *ResumeReply) ProtoReflect() protoreflect.Message {
	mi := &file_resume_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeReply.ProtoReflect.Descriptor instead.
func (*ResumeReply) Descriptor() ([]byte, []int) {
	return file_resume_proto_rawDescGZIP(), []int{1}
}

func (x *ResumeReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResumeReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

//-----------------------获取基本信息 start------------------
type BaseInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BaseInfoRequest) Reset() {
	*x = BaseInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resume_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfoRequest) ProtoMessage() {}

func (x *BaseInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfoRequest.ProtoReflect.Descriptor instead.
func (*BaseInfoRequest) Descriptor() ([]byte, []int) {
	return file_resume_proto_rawDescGZIP(), []int{2}
}

func (x *BaseInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseInfoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OutBaseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VName      string `protobuf:"bytes,2,opt,name=v_name,json=vName,proto3" json:"v_name,omitempty"`
	VSex       string `protobuf:"bytes,3,opt,name=v_sex,json=vSex,proto3" json:"v_sex,omitempty"`
	VPhone     string `protobuf:"bytes,4,opt,name=v_phone,json=vPhone,proto3" json:"v_phone,omitempty"`
	VAge       string `protobuf:"bytes,5,opt,name=v_age,json=vAge,proto3" json:"v_age,omitempty"`
	VEmail     string `protobuf:"bytes,6,opt,name=v_email,json=vEmail,proto3" json:"v_email,omitempty"`
	VEducation string `protobuf:"bytes,7,opt,name=v_education,json=vEducation,proto3" json:"v_education,omitempty"`
}

func (x *OutBaseInfo) Reset() {
	*x = OutBaseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resume_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutBaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutBaseInfo) ProtoMessage() {}

func (x *OutBaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_resume_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutBaseInfo.ProtoReflect.Descriptor instead.
func (*OutBaseInfo) Descriptor() ([]byte, []int) {
	return file_resume_proto_rawDescGZIP(), []int{3}
}

func (x *OutBaseInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OutBaseInfo) GetVName() string {
	if x != nil {
		return x.VName
	}
	return ""
}

func (x *OutBaseInfo) GetVSex() string {
	if x != nil {
		return x.VSex
	}
	return ""
}

func (x *OutBaseInfo) GetVPhone() string {
	if x != nil {
		return x.VPhone
	}
	return ""
}

func (x *OutBaseInfo) GetVAge() string {
	if x != nil {
		return x.VAge
	}
	return ""
}

func (x *OutBaseInfo) GetVEmail() string {
	if x != nil {
		return x.VEmail
	}
	return ""
}

func (x *OutBaseInfo) GetVEducation() string {
	if x != nil {
		return x.VEducation
	}
	return ""
}

type BaseInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*OutBaseInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *BaseInfoReply) Reset() {
	*x = BaseInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resume_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfoReply) ProtoMessage() {}

func (x *BaseInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_resume_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfoReply.ProtoReflect.Descriptor instead.
func (*BaseInfoReply) Descriptor() ([]byte, []int) {
	return file_resume_proto_rawDescGZIP(), []int{4}
}

func (x *BaseInfoReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseInfoReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BaseInfoReply) GetData() []*OutBaseInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

//-----------------------获取简历信息 start------------------
type ResumeInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SearchKey string `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
}

func (x *ResumeInfoRequest) Reset() {
	*x = ResumeInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resume_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeInfoRequest) ProtoMessage() {}

func (x *ResumeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeInfoRequest.ProtoReflect.Descriptor instead.
func (*ResumeInfoRequest) Descriptor() ([]byte, []int) {
	return file_resume_proto_rawDescGZIP(), []int{5}
}

func (x *ResumeInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResumeInfoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResumeInfoRequest) GetSearchKey() string {
	if x != nil {
		return x.SearchKey
	}
	return ""
}

type OutResumeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VBaseId      string `protobuf:"bytes,2,opt,name=v_base_id,json=vBaseId,proto3" json:"v_base_id,omitempty"`
	VStartDate   string `protobuf:"bytes,3,opt,name=v_start_date,json=vStartDate,proto3" json:"v_start_date,omitempty"`
	VEndDate     string `protobuf:"bytes,4,opt,name=v_end_date,json=vEndDate,proto3" json:"v_end_date,omitempty"`
	VWordContent string `protobuf:"bytes,5,opt,name=v_word_content,json=vWordContent,proto3" json:"v_word_content,omitempty"`
	VPosition    string `protobuf:"bytes,6,opt,name=v_position,json=vPosition,proto3" json:"v_position,omitempty"`
}

func (x *OutResumeInfo) Reset() {
	*x = OutResumeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resume_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutResumeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutResumeInfo) ProtoMessage() {}

func (x *OutResumeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_resume_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutResumeInfo.ProtoReflect.Descriptor instead.
func (*OutResumeInfo) Descriptor() ([]byte, []int) {
	return file_resume_proto_rawDescGZIP(), []int{6}
}

func (x *OutResumeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OutResumeInfo) GetVBaseId() string {
	if x != nil {
		return x.VBaseId
	}
	return ""
}

func (x *OutResumeInfo) GetVStartDate() string {
	if x != nil {
		return x.VStartDate
	}
	return ""
}

func (x *OutResumeInfo) GetVEndDate() string {
	if x != nil {
		return x.VEndDate
	}
	return ""
}

func (x *OutResumeInfo) GetVWordContent() string {
	if x != nil {
		return x.VWordContent
	}
	return ""
}

func (x *OutResumeInfo) GetVPosition() string {
	if x != nil {
		return x.VPosition
	}
	return ""
}

type ResumeInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*OutResumeInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ResumeInfoReply) Reset() {
	*x = ResumeInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resume_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeInfoReply) ProtoMessage() {}

func (x *ResumeInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_resume_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeInfoReply.ProtoReflect.Descriptor instead.
func (*ResumeInfoReply) Descriptor() ([]byte, []int) {
	return file_resume_proto_rawDescGZIP(), []int{7}
}

func (x *ResumeInfoReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResumeInfoReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResumeInfoReply) GetData() []*OutResumeInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_resume_proto protoreflect.FileDescriptor

var file_resume_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x22, 0x71, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x70, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x70, 0x41, 0x64, 0x64,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3b, 0x0a, 0x0b, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3f, 0x0a, 0x0f, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xb1, 0x01, 0x0a, 0x0b, 0x4f, 0x75, 0x74, 0x42,
	0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x76, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x13,
	0x0a, 0x05, 0x76, 0x5f, 0x73, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76,
	0x53, 0x65, 0x78, 0x12, 0x17, 0x0a, 0x07, 0x76, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x13, 0x0a, 0x05,
	0x76, 0x5f, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x41, 0x67,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x76, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x76, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x5f,
	0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x76, 0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x66, 0x0a, 0x0d, 0x42,
	0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x2e, 0x4f, 0x75, 0x74, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x60, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x4b, 0x65, 0x79, 0x22, 0xc0, 0x01, 0x0a, 0x0d, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x09, 0x76, 0x5f, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x42, 0x61, 0x73,
	0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x76, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x0a, 0x76, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x45, 0x6e, 0x64, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x76, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x76, 0x57, 0x6f,
	0x72, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x5f, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6a, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x2e, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x32, 0xce, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x12,
	0x3c, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x15, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3f, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x2e, 0x72,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x42,
	0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x45,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x19, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x72, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_resume_proto_rawDescOnce sync.Once
	file_resume_proto_rawDescData = file_resume_proto_rawDesc
)

func file_resume_proto_rawDescGZIP() []byte {
	file_resume_proto_rawDescOnce.Do(func() {
		file_resume_proto_rawDescData = protoimpl.X.CompressGZIP(file_resume_proto_rawDescData)
	})
	return file_resume_proto_rawDescData
}

var file_resume_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_resume_proto_goTypes = []interface{}{
	(*ResumeRequest)(nil),     // 0: resume.ResumeRequest
	(*ResumeReply)(nil),       // 1: resume.ResumeReply
	(*BaseInfoRequest)(nil),   // 2: resume.BaseInfoRequest
	(*OutBaseInfo)(nil),       // 3: resume.OutBaseInfo
	(*BaseInfoReply)(nil),     // 4: resume.BaseInfoReply
	(*ResumeInfoRequest)(nil), // 5: resume.ResumeInfoRequest
	(*OutResumeInfo)(nil),     // 6: resume.OutResumeInfo
	(*ResumeInfoReply)(nil),   // 7: resume.ResumeInfoReply
}
var file_resume_proto_depIdxs = []int32{
	3, // 0: resume.BaseInfoReply.data:type_name -> resume.OutBaseInfo
	6, // 1: resume.ResumeInfoReply.data:type_name -> resume.OutResumeInfo
	0, // 2: resume.Resume.ResumeServer:input_type -> resume.ResumeRequest
	2, // 3: resume.Resume.GetBaseInfo:input_type -> resume.BaseInfoRequest
	5, // 4: resume.Resume.GetResumeInfo:input_type -> resume.ResumeInfoRequest
	1, // 5: resume.Resume.ResumeServer:output_type -> resume.ResumeReply
	4, // 6: resume.Resume.GetBaseInfo:output_type -> resume.BaseInfoReply
	7, // 7: resume.Resume.GetResumeInfo:output_type -> resume.ResumeInfoReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_resume_proto_init() }
func file_resume_proto_init() {
	if File_resume_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resume_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resume_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resume_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resume_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutBaseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resume_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resume_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resume_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutResumeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resume_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resume_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resume_proto_goTypes,
		DependencyIndexes: file_resume_proto_depIdxs,
		MessageInfos:      file_resume_proto_msgTypes,
	}.Build()
	File_resume_proto = out.File
	file_resume_proto_rawDesc = nil
	file_resume_proto_goTypes = nil
	file_resume_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ResumeClient is the client API for Resume service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResumeClient interface {
	ResumeServer(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeReply, error)
	GetBaseInfo(ctx context.Context, in *BaseInfoRequest, opts ...grpc.CallOption) (*BaseInfoReply, error)
	GetResumeInfo(ctx context.Context, in *ResumeInfoRequest, opts ...grpc.CallOption) (*ResumeInfoReply, error)
}

type resumeClient struct {
	cc grpc.ClientConnInterface
}

func NewResumeClient(cc grpc.ClientConnInterface) ResumeClient {
	return &resumeClient{cc}
}

func (c *resumeClient) ResumeServer(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeReply, error) {
	out := new(ResumeReply)
	err := c.cc.Invoke(ctx, "/resume.Resume/ResumeServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resumeClient) GetBaseInfo(ctx context.Context, in *BaseInfoRequest, opts ...grpc.CallOption) (*BaseInfoReply, error) {
	out := new(BaseInfoReply)
	err := c.cc.Invoke(ctx, "/resume.Resume/GetBaseInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resumeClient) GetResumeInfo(ctx context.Context, in *ResumeInfoRequest, opts ...grpc.CallOption) (*ResumeInfoReply, error) {
	out := new(ResumeInfoReply)
	err := c.cc.Invoke(ctx, "/resume.Resume/GetResumeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResumeServer is the server API for Resume service.
type ResumeServer interface {
	ResumeServer(context.Context, *ResumeRequest) (*ResumeReply, error)
	GetBaseInfo(context.Context, *BaseInfoRequest) (*BaseInfoReply, error)
	GetResumeInfo(context.Context, *ResumeInfoRequest) (*ResumeInfoReply, error)
}

// UnimplementedResumeServer can be embedded to have forward compatible implementations.
type UnimplementedResumeServer struct {
}

func (*UnimplementedResumeServer) ResumeServer(context.Context, *ResumeRequest) (*ResumeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeServer not implemented")
}
func (*UnimplementedResumeServer) GetBaseInfo(context.Context, *BaseInfoRequest) (*BaseInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBaseInfo not implemented")
}
func (*UnimplementedResumeServer) GetResumeInfo(context.Context, *ResumeInfoRequest) (*ResumeInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResumeInfo not implemented")
}

func RegisterResumeServer(s *grpc.Server, srv ResumeServer) {
	s.RegisterService(&_Resume_serviceDesc, srv)
}

func _Resume_ResumeServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServer).ResumeServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resume.Resume/ResumeServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServer).ResumeServer(ctx, req.(*ResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resume_GetBaseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServer).GetBaseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resume.Resume/GetBaseInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServer).GetBaseInfo(ctx, req.(*BaseInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resume_GetResumeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServer).GetResumeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resume.Resume/GetResumeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServer).GetResumeInfo(ctx, req.(*ResumeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Resume_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resume.Resume",
	HandlerType: (*ResumeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResumeServer",
			Handler:    _Resume_ResumeServer_Handler,
		},
		{
			MethodName: "GetBaseInfo",
			Handler:    _Resume_GetBaseInfo_Handler,
		},
		{
			MethodName: "GetResumeInfo",
			Handler:    _Resume_GetResumeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resume.proto",
}
